name: build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-shellcheck@v1
        with:
          reporter: github-pr-review
          path: tools
          pattern: "*.bash"
  fmt:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-go
      - run: make fmt-check
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-go
      - run: make test
  docscheck:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'push' &&
      github.head_ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-go
      - run: make generate
      - run: git diff --exit-code --name-only
  goreleaser:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-go
      - uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: build --snapshot --rm-dist
      - uses: actions/upload-artifact@v3
        with:
          name: providers
          path: dist/*
